version: '3'

services:
  php-app:
    build: ./src
    ports:
      - "8000:80"
    depends_on:
      - mysql-db


  mysql-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: hive
       MYSQL_ALLOW_EMPTY_PASSWORD: Yes
       MYSQL_PASSWORD: password 
    volumes:
      - mysql-data:/var/lib/mysql


  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080


  sonarqube:
    image: sonarqube:community
    depends_on:
      - mysql-db
    ports:
      - "9000:9000"
  

volumes:
  mysql-data: