version: '3'

services:
  php-app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: hive
       MYSQL_ALLOW_EMPTY_PASSWORD: Yes
       MYSQL_PASSWORD: ""
    volumes:
      - mysql-data:/var/lib/mysql

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080

volumes:
  mysql-data: