version: '3.1'
services:
    php:
        image: php:apache
        ports:
        - 8000:80
        volumes:
        - ../../itvb23ows-starter-code:/var/www/html/
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: Hive
            MYSQL_ALLOW_EMPTY_PASSWORD: Yes
            MYSQL_PASSWORD: ""
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
