version: '3'

services:
  php-app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: hive
       MYSQL_PASSWORD: password 
       MYSQL_USER: username
    volumes:
      - ./Database:/docker-entrypoint-initdb.d

  jenkins:
    build: ./jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock


  sonarqube:
    image: sonarqube:community
    depends_on:
      - mysql-db
    ports:
      - "9000:9000"
  

volumes:
  mysql-data: